### ISSUE TITLE
Mageia 7.1 Review Request

### ISSUE THREAD

**Issue by Reiddragon** [egee-irl/distro-delves#10]
## Name & tl;dr
Mageia 7.1

## What is the release date or cycle?
When it's ready™

## Who is the target user?
Desktop and Server users

## What platforms does it support?
i586, AMD64

## What makes it special?
Mandriva's other spiritual succesor. Not much else to say.

**Comment by egee-irl** [comment]
It looks like Mageia 7.1 was released back in July of 2019 so I'll probably review it once it hits 7.2 or whatever the next version is

**Comment by egee-irl** [comment]
@Reiddragon I'm trying to find release notes or info about the latest minor release or bug fixes but I can't seem to find any.

Is it worth waiting until the next big release or should I look at it now without additional information?
