### ISSUE TITLE
Functional O.S.

### ISSUE THREAD

**Issue by LouieTian0209** [egee-irl/distro-delves#100]
## Name & tl;dr

Functional O.S.
Official Website: [https://www.functional.altervista.org/](https://www.functional.altervista.org/)
Download Link (also to be found at the bottom of the official website): [http://www.mediafire.com/file/ut3jlhvwavnisfz/enterprise.iso/file](http://www.mediafire.com/file/ut3jlhvwavnisfz/enterprise.iso/file)
## What is the release date or cycle?

Unknown
## Who is the target user?

Users in work or home environment
## What platforms does it support?

x64
## What makes it special?

The claim "The universal operating system for offices and home" is bold and interesting, also the distro name is direct. Weirdly it's called Functional O.S. all over the website but the iso is named "enterprise"

**Comment by H3LLC47** [comment]
It's definitely interesting. I tried this out about a month ago.

**Comment by egee-irl** [comment]
This looks awesome, I'll definitely keep my eye on it

**Comment by egee-irl** [comment]
This appears to be dead maybe?

**Comment by LouieTian0209** [comment]
> This appears to be dead maybe?

Looks like that's the case. Homepage is down and download link is broken too. I'll close this request and feel free to look at another request I just created about MakuluLinux and their latest LinDoz version.
