### ISSUE TITLE
Involve Egee-to-use Toolkit in the script

### ISSUE THREAD

**Issue by dominichayesferen** [egee-irl/distro-delves#104]
## Add, Remove, or Update?
Add the following to the end of the script:

1. Egee-to-use Toolkit Stress Testers + other Stress Testers if desired
2. Visual Payload from Egee-to-use Toolkit
3. Check for any prerequisites for Egee-to-use Toolkit ahead of running the script (Discord channel)
4. (FINALE) Random payload from Egee's Destroyer or more than one payload

## Which Segment?
Near the end of the script

## Rationale?
It would be good to give the stress testers some use, and also if you put to check for prerequisites in the script then that should make things much easier on all of us.

**Comment by egee-irl** [comment]
I shall naught.
