### ISSUE TITLE
MakuluLinux LinDoz Edition 2021.02.14

### ISSUE THREAD

**Issue by LouieTian0209** [egee-irl/distro-delves#107]
## Name & tl;dr
MakuluLinux LinDoz Edition 2021.02.14 Barebone/Complete
Barebone version download link: [https://drive.google.com/file/d/1alg61P1Sjh0rQIXLNK5Hlv7v21ljYjO9/view?usp=sharing](https://drive.google.com/file/d/1alg61P1Sjh0rQIXLNK5Hlv7v21ljYjO9/view?usp=sharing)
Complete version download link: [https://drive.google.com/file/d/1ZkaBLGq5JOqz4GnHoC4jwWpgb9gS2fkD/view?usp=sharing](https://drive.google.com/file/d/1ZkaBLGq5JOqz4GnHoC4jwWpgb9gS2fkD/view?usp=sharing)

Here's the difference between Barebone and Complete versions (from the developer himself):
Barebone Build - is exactly as the name suggests, it has very little custom software pre installed, leaving a lot of that to be done by the user himself, expert users will love this build. The barebone build is also the only build between the two that is compatible with Virtualbox. However both builds are compatible with Vmware.

Complete Build - is exactly as the name suggests, it is more complete with software pre installed including an  Office suite, Wine, steam and all the required libraries... all preconfigured. The Complete build is compatible with Vmware, but NOT with virtualbox.

(This 2021.02.14 build is the actual release version of current MakuluLinux LinDoz, not much has changed from previous 2021.01.29 version besides some packages updates as far as I'm aware)

## What is the release date or cycle?
N/A, release whenever a version is ready

## Who is the target user?
Desktop Linux users

## What platforms does it support?
x64

## What makes it special?
LinDoz started as a Windows clone but recently the developer has announced that they're moving away from their original decision and instead of focusing on making a Windows clone, they want to make LinDoz an unique distro in its own way but at the same time it's still somewhat familiar to those coming from Windows.

**Comment by egee-irl** [comment]
I'll be looking at this on live hardware. Which should we test - Barebones or Complete?

**Comment by dominichayesferen** [comment]
> I'll be looking at this on live hardware. Which should we test - Barebones or Complete?

I'd say complete, 'cos, uh, **complete** experience. (that being said complete likely means most bloated given the usual rule)

**Comment by LouieTian0209** [comment]
@egee-irl Just updated download link and version number to the latest release version. If you haven't downloaded the iso for live stream you'll be downloading the latest version.
