### ISSUE TITLE
CloudReady (Neverware)

### ISSUE THREAD

**Issue by aobhgoleor** [egee-irl/distro-delves#11]
## Name & tl;dr

CloudReady (Neverware), ver 78.4 (I think)

## What is the release date or cycle?

Rolling Release

## Who is the target user?

There's 3 edition of CloudReady; Enterprise (Paid), Education (Paid), & Home/Personal (free); the Home edition is for "parents, students, a fans, or just someone ready for a better OS" so I imagine it's for general users who do non-technical activities

**Comment by egee-irl** [comment]
This is an interesting one. I could see this being a "special episode" since I don't think it will pass most of the checklist segments, but would still be fun to do.

**Comment by aobhgoleor** [comment]
@egee-irl i should give you a heads up, since CloudReady is based on ChromiumOS you do need a google account to use it

**Comment by natri23** [comment]
> This is an interesting one. I could see this being a "special episode" since I don't think it will pass most of the checklist segments, but would still be fun to do.

I think you might be surprised

**Comment by egee-irl** [comment]
I looked into this a few weeks ago and found it to be cumbersome to get setup. It might be difficult to make it a regular episode.

**Comment by natri23** [comment]
Also it should be better installed on a laptop. The experience is miles better, especially the multitouch gestures which Linux haven't figured out yet

**Comment by egee-irl** [comment]
I researched more into Neverware and it's super interesting but it's something I would want to include in a Chromebook/ChromeOS mini-series.

I'm going to keep this issue in mind and try to get my hands on a Chromebook to compare it against. I think it would be a super fun episode!

**Comment by natri23** [comment]
You might also want to check out Brunch Chrome OS project as well:
https://github.com/sebanc/brunch

**Comment by natri23** [comment]
The reason I'm using it on my laptop instead of Linux is Macbook-level touchpad drivers and Hardware acceleration in Chrome.
The experience is unmatched...

**Comment by natri23** [comment]
There's also a package manager for ChromeOS from some serious dev

https://github.com/skycocker/chromebrew

![image](https://user-images.githubusercontent.com/1286842/103151498-20341600-47b1-11eb-85b2-db4b9588737a.png)

**Comment by egee-irl** [comment]
This is next on the list. Anything, in particular, you want me to focus on with this one? It's a strange one!

**Comment by natri23** [comment]
It would be best experienced on a laptop due to multi-touch gestures but I understand it might not be possible. Some links you might find useful: 
https://support.google.com/chromebook/answer/1056325
https://support.google.com/chrome/answer/9658361?co=GENIE.Platform%3DAndroid&hl=en

**Comment by aobhgoleor** [comment]
nothing in particular, but after you get done I would recommended looking at the partitions it makes; its a very interesting partition system setup lmao.

**Comment by egee-irl** [comment]
We reviewed this distro but the video is still private because there is a lot to edit out. I have no ETA when I will finish it :(

We may revisit CloudReady in the future now that I know what to expect.
