### ISSUE TITLE
Sparky Linux (Semi-)Rolling

### ISSUE THREAD

**Issue by ukbeast** [egee-irl/distro-delves#111]
## Name & tl;dr
[SparkyLinux](https://sparkylinux.org/) is a GNU/Linux distribution created on the top of Debian GNU/Linux operating system; fast, lightweight and fully customizable OS which offers a few versions for different users and different tasks.
## What is the release date or cycle?
[Based on Debian testing branch](https://sparkylinux.org/download/rolling/)

## Who is the target user?
Sparky “rolling (testing) flavor” is targeted to more advanced users, whose don’t afraid of a little less stable version of applications, and want to work with/on latest version of offered the software.
 – special editions: GameOver(Gaming edition), Multimedia & Rescue

## What platforms does it support?
x86_64/amd64

## What makes it special?
• 3 Special Editions for different tasks:
* GameOver for gamers (Xfce);
* Multimedia for audio, video and html pages creating (Xfce);
* Rescue for fixing broken OS or so (Openbox)

Own repository with a large set of additional applications and has codecs installed out the box.

**Comment by egee-irl** [comment]
We looked at this on stream but not very well. Go ahead and make a new issue for Sparky for the next release and I'll dedicate a full length stream to it.
