### ISSUE TITLE
SolydXK

### ISSUE THREAD

**Issue by hack13** [egee-irl/distro-delves#12]
## Name & tl;dr
SolydXK

## What is the release date or cycle?
Every 2 years, with 5 year support for each release. (Debian Based)

## Who is the target user?
Claim is for small business and home users who want a stable system

## What platforms does it support?
x64 only

## What makes it special?
A distribution that is claims to be very stable and user friendly system. It comes in two flavours X or K, xfce or KDE. Something designed to stand out not in the way a lot of distributions do, but in a way for a system that just is out of your way and user friendly to just get work done on a base that is rock solid.

**Comment by egee-irl** [comment]
Interesting, I'll keep my eye on this one

**Comment by egee-irl** [comment]
It looks like the most recent SolydXK release was December of 2019. I'll wait until the next release to take a look at it.

**Comment by egee-irl** [comment]
@hack13 I'm unsure if this project is alive anymore. The isos are almost a year old (09-2019) and the "professional services" [link](https://solydxk.nl/) goes to a Plesk control panel.

Unless you think it's still worth looking at, I'm probably going to close this issue and wait for the next release.

**Comment by hack13** [comment]
I will close this, as it does seem dead...
