### ISSUE TITLE
GhostBSD or FuryBSD

### ISSUE THREAD

**Issue by Mcpower03** [egee-irl/distro-delves#13]
## Name & tl;dr
GhostBSD and FuryBSD seem to be a desktop bsd "distros" if you will.

## What is the release date or cycle?

Not fully sure
## Who is the target user?

Desktop users
## What platforms does it support?

X86
## What makes it special?

I mean, its bsd. Its something different from linux to try

**Comment by egee-irl** [comment]
These are definitely on the list of "distros" to look at. Every excited to check these out

**Comment by Mcpower03** [comment]
Midnight and NomadBSD I think are sort of in the same category

**Comment by egee-irl** [comment]
GhostBSD is DONEZO
