### ISSUE TITLE
Septor

### ISSUE THREAD

**Issue by Waffelo** [egee-irl/distro-delves#134]
## Name & tl;dr
[Septor 2021.3](https://septor.sourceforge.io/)
## What is the release date or cycle?
It looks like to be rolling release.

## Who is the target user?
It is made for people that want to browse internet anonymously.

## What platforms does it support?
amd64

## What makes it special?
It is a privacy focused distro with few privacy tools installed.

**Comment by egee-irl** [comment]
Thank you for your submission <3
