### ISSUE TITLE
Peppermint OS 11

### ISSUE THREAD

**Issue by kuneljo** [egee-irl/distro-delves#137]
## Name & tl;dr
Peppermint OS 11

## What is the release date or cycle?
Had been stalled since 2019, now a new Version based on Debian Stable is out. So, maybe Debian Stable release cycle from now on..?

## Who is the target user?
Everyday normal person

## What platforms does it support?
x86_64

## What makes it special?
It has been a popular and well-liked distro, then due to a tragic event the development got stalled and at least I saw little chance of a comeback. But now a new version was released with massive changes, most importantly switching to Debian (from Ubuntu) and Xfce (from LXDE). They also make some interesting choices, e.g. regarding the file manager.

**Comment by egee-irl** [comment]
Guess what distro is up for live review! Anything else I should be aware of with this one @kuneljo ?

**Comment by jKuenel** [comment]
@egee-irl nice! I heard some negative opinions about the new version, mostly that it's not that lightweight and snappy anymore, and especially lags behind other Debian -based distros. Normally I wouldn't care, but this was the main selling point in the past, so maybe you could pay attention to that.

**Comment by kuneljo** [comment]
@egee-irl nice! I heard some negative opinions about the new version, mostly that it's not that lightweight and snappy anymore, and especially lags behind other Debian -based distros. Normally I wouldn't care, but this was the main selling point in the past, so maybe you could pay attention to that.
