### ISSUE TITLE
Arch Zen Installer?

### ISSUE THREAD

**Issue by Mcpower03** [egee-irl/distro-delves#15]
## Name & tl;dr

The zen installer seems to implement a lot of the stuff a distro like endeavor might have, so why not try a stock arch installer, it is graphical after all
## What is the release date or cycle?

Not really sure what the release cycle is, but it's arch
## Who is the target user?

I guess people who don't want the terminal installer?
## What platforms does it support?

x86
## What makes it special?

It's vanilla arch, but with a graphical installer

**Comment by egee-irl** [comment]
This is an interesting idea - I get requests to cover vanilla Arch all the time. @Mcpower03 do you think the Zen installer could pass as a "Vanilla Arch" install?

**Comment by Mcpower03** [comment]
I'm not sure, but I think in the end you kind of end up with the same thing. I would think that maybe vanilla arch isn't really fit for distro selves, but this seemed like kind of an inbetween

**Comment by ishan9299** [comment]
You can also try the archfi script. But remember two give users a warning as they are not the recommended way to install arch. Because if devs change something upstream these installer would require an update to be functional.

**Comment by egee-irl** [comment]
So far, the Zen Installer episode has been a disaster.

I won't be covering Arch again as it doesn't fit the purpose of the series
