### ISSUE TITLE
KDE Neon 5.18.5

### ISSUE THREAD

**Issue by TheRealKizu** [egee-irl/distro-delves#16]
## Name & tl;dr

KDE Neon 5.18.5

## What is the release date or cycle?

The ISO's are built weekly, but sometimes there may be an issue preventing it, say a problem with the automation, or various components don't build, or failed tests.

## Who is the target user?

To users who want to experience the latest Plasma release in a distro form.

## What platforms does it support?

x64 only.

## What makes it special?

KDE neon provides an easy and elegant way for people to test the latest from KDE, or use the latest releases of KDE Software.

**Comment by TrackRunny** [comment]
Agreed, lets try and get KDE Neon on this. I really do love what they have going for it compared to other distros.

**Comment by egee-irl** [comment]
I've been thinking of leaving KDE Neon until the next Ubuntu LTS releases. Do you guys think that is too long of a wait? Should I look at KDE Neon now?

**Comment by TheRealKizu** [comment]
You should :D

**Comment by egee-irl** [comment]
Do we have a release date for the next Neon based on 20.04?

**Comment by TheRealKizu** [comment]
[Here](https://community.kde.org/Schedules/release_service/20.04_Release_Schedule#Thursday.2C_April_23.2C_2020:_20.04_Release)

**Comment by egee-irl** [comment]
Cleaning up the backlog - this one is in prog so I'm closing this issue
