### ISSUE TITLE
Pop os

### ISSUE THREAD

**Issue by Ahmedmexx** [egee-irl/distro-delves#17]
yes
## Name & tl;dr

Pop!_OS 19.10
## What is the release date or cycle?

ubuntu LTS or interim release of Ubuntu, with 19.10 example
## Who is the target user?

an OS for the software developer, maker, and computer science professional who uses their computer as a tool to discover and create.
## What platforms does it support?

Pop!_OS only runs on 64-bit x86 architecture
## What makes it special?

Pop!_OS encrypts your installation by default and is the only distro that enables full-disk encryption out-of-the box from System76. A unique and private encryption key is generated during setup after you receive your computer.

**Comment by egee-irl** [comment]
I'm planning to wait to review Pop_OS until the next Ubuntu LTS release. So, hopefully System76 updates it quickly so we can get Pop_OS on Distro Delves right away!
