### ISSUE TITLE
Ubuntu Cinnamon 19.10

### ISSUE THREAD

**Issue by KaiLyons** [egee-irl/distro-delves#19]
## Ubuntu Cinnamon
Two ways to link about it:
- Less bloated Ubuntu with Cinnamon 
- Less "bloated" Linux Mint

## What is the release date or cycle?
Every 6 months with the Ubuntu release cycle (April, October)

## Who is the target user?
People who want to use an Ubuntu-based distro with a solid Cinnamon finish without the extra stuff given by Linux Mint

## What platforms does it support?
AMD64 / x86_64

## What makes it special?
It is pretty much brand new, with the first release being 19.10

**Comment by egee-irl** [comment]
So I looked into Ubuntu Cinnamon and it looks like the 19.10 release was an alpha or beta. The install was pretty rough and I don't have the bandwidth to look at alpha/beta/RC releases on the series.

**Comment by egee-irl** [comment]
I'm cleaning up issues and since this is for 19.10, I'm going to close it. Feel free to open one for 20.04 but people seem to be burned out on Ubuntu distros so it might be better to wait until 20.10
