### ISSUE TITLE
Q4OS

### ISSUE THREAD

**Issue by Commander-Zal** [egee-irl/distro-delves#2]
## Name & tl;dr

[Q4OS](https://q4os.org/index.html) - Version 3.10 'Centuarus' Trinity Edition

## What is the release date or cycle?

5 Year release cycle based on Debian Stable. 
Version 3.10 was released on January 4th 2020.

## Who is the target user?

I suspect it's targeted at Debian users who want a better out-of-the-box experience similar to Ubuntu, with the Trinity edition more specifically targeted at users who miss KDE 3 (Trinity being a maintained fork of KDE 3, similar to MATE being a fork of Gnome 2). It also may target Windows XP and Windows 7 converts.

## What platforms does it support?

x86, x64, and ARM.

## What makes it special?

Q4OS is one of the very few distros that offer the Trinity DE, and the **only** distro shipping the Trinity DE as a first-class experience. It also has a KDE 5 version, but the Trinity edition is what makes it stand out, and should make for an interesting delve.

**Comment by egee-irl** [comment]
Ohh this looks like an interesting one. I'm pretty sure I've heard of it before, too. I'll add it to the backlog!

**Comment by creepertron95** [comment]
I used to use this in a VM before discovering MX. By default, most of the customization features in Q4OS (Theme settings, Icon settings, Colors) are locked and you have to input `$ sudo kcmodules --unlock` to unlock all of the customization settings Q4OS has to offer.

**Comment by egee-irl** [comment]
I'm looking at this one today!
