### ISSUE TITLE
openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Sentosa2012** [egee-irl/distro-delves#20]
## Name & tl;dr
openSUSE Tumbleweed - A distro backed by an open source focused company (SUSE)

## What is the release date or cycle?
Rolling Release with "snapshot" releases every month

## Who is the target user?
Intermediate level desktop/workstation users. Its definitely not for new users and has a lot of workstation DNA but is suitable 

## What platforms does it support?
x86_64, i586, arm64/aarch64

## What makes it special?
- Very Powerful
- Yast
- Enterprise Backing
- Installer provides a ton of options
- Similar package management to that of Fedora

**Comment by egee-irl** [comment]
Definitely on the list

**Comment by papasfilmsofficial** [comment]
That was the distro I was going to submit now!!! I guess thank you!

**Comment by egee-irl** [comment]
@papasfilmsofficial @Sentosa2012 Which DE should I look at? Thinking between KDE or Gnome

**Comment by papasfilmsofficial** [comment]
I prefer KDE but it had some problems on a vm (I know you don't test them on a vm)

**Comment by Sentosa2012** [comment]
I'd say KDE. It feels a bit more fully baked than Gnome. Although not to the same level as KDE Neon, it seems like its their "flagship" option

**Comment by Sentosa2012** [comment]
@egee-irl I forgot to mention, by default openSUSE doesn't come with support for many codex out of the box because "licencing" or something. You'd need to enable the Packman repo from either YaST or Zypper and sync with that repository.

**Comment by ishan9299** [comment]
> I'd say KDE. It feels a bit more fully baked than Gnome. Although not to the same level as KDE Neon, it seems like its their "flagship" option

what I have heard from the devs on reddit both options are fully supported as a flagship but there are more kde devs who work with opensuse.
