### ISSUE TITLE
Encryption during install

### ISSUE THREAD

**Issue by egee-irl** [egee-irl/distro-delves#22]
## Add, Remove, or Update?
Addition

## Which Segment?
Install

## Rationale?
Testing encryption during the install seems like it would be a cool thing to test

**Comment by Mcpower03** [comment]
Testing how so?

**Comment by egee-irl** [comment]
Seeing how (or _if_) a distro's installer handles encryption, and seeing how the distro itself handles it. And also, if it has any performance impact on the benchmarks!

**Comment by Mcpower03** [comment]
I feel that would be a worthwhile inclusion to the script
