### ISSUE TITLE
General snappiness

### ISSUE THREAD

**Issue by InstantCurry** [egee-irl/distro-delves#26]
## Add, Remove, or Update?
Addition

## Which Segment?
Install and resources or Desktop and apps

## Rationale?
We all subconsciously look for and judge while look for a distro to use is the general responsiveness, how fast menus and widgets open, whether any desktop effects are laggy, and so on. Unfortunately, this isn't the easiest to quantify, but maybe the milliseconds it takes to open various widgets or something like that. 

Note: I know this is somewhat dependant on hardware, even moving from kubuntu to neon shows a difference in "snappiness", so I think it's worth looking at.

**Comment by egee-irl** [comment]
hm I don't know how I would test or "check" for this. I suppose I could look at window snapping or something?

**Comment by InstantCurry** [comment]
I was think more of ms to open various application and widgets, but I guess that's easier to quantify. To be honest this suggestion is a bit odd anyway so anything goes, I guess.

**Comment by egee-irl** [comment]
Since there's no standard way of calculating this, I'm going to close this task
