### ISSUE TITLE
theShell

### ISSUE THREAD

**Issue by KaiLikesLinux** [egee-irl/distro-delves#27]
## theShell

Version: ??
Website: https://vicr123.com/theshell/os/
Direct ISO: https://sourceforge.net/projects/theos/files/theshellos-2018.07.04-x86_64-preview.iso/download

## What is the release date or cycle?
Not a clue, even the SourceForge has very little information. It *might* be deprecated, but I am unsure.

## Who is the target user?

Desktop user

## What platforms does it support?

arm64

## What makes it special?

It has its own desktop they made, under the same name!

**Comment by egee-irl** [comment]
Oh man, what even is this hahaha

**Comment by egee-irl** [comment]
Ok this looks awesome - I'm going to try it in a VM and see if its viable

**Comment by egee-irl** [comment]
Scratch that - the "latest" iso is from 2018 :(
