### ISSUE TITLE
UbuntuDDE Remix 20.04

### ISSUE THREAD

**Issue by cescript** [egee-irl/distro-delves#28]
## UbuntuDDE
UbuntuDDE is a linux distro based on Ubuntu 20.04 with Deepin desktop environment.

## What is the release date or cycle?
UbuntuDDE Remix 20.04 released its beta version on 06 April 2020. Official stable release will probably be released with the release of Ubuntu 20.04.

## Who is the target user?
Anyone who looks for beautiful desktop environments and loves Ubuntu.

## What platforms does it support?
x64

## What makes it special?
All the Ubuntu community and package advantages are wrapped with the Deepin desktop environment.

**Comment by KaiLikesLinux** [comment]
I actually know the dev of UbuntuDDE personally. Then again being the developer of Ubuntu Lumina kind of helps

**Comment by egee-irl** [comment]
I'm cleaning up issues and since this is for 20.04, I'm going to close it. Feel free to open one for 20.10 when it comes out
