### ISSUE TITLE
Clear Linux

### ISSUE THREAD

**Issue by Tiixxel** [egee-irl/distro-delves#29]
## Clear Linux
Clear Linux OS is an open source, rolling release Linux distribution optimized for performance and security, from the Cloud to the Edge, designed for customization, and manageability. 

## What is the release date or cycle?
The first Clear Linux version was released in 2015 with the Xfce desktop environment being preinstalled. After 2 revisions with the switch to GNOME as a DE, it is now available for regular desktop users. 

## Who is the target user?
Clear Linux aims at desktop and server users having an Intel CPU in their system who want
performance, security, customization and manageability.

## What platforms does it support?
Clear Linux does only support x86_64 CPU's.

## What makes it special?
Clear Linux is special because it is the most robust rolling release distribution out there due to the way it handle's updates and packages. It is also one of the most performant distribution's for Intel CPU's because Intel themselves are using an own kernel with optimization inside of it.

**Comment by egee-irl** [comment]
The main reason I've avoided Clear Linux is that it doesn't have a friendly installer, let alone a desktop or coherent package management system for an end-user.

However, it looks like this has changed? The website looks totally different than what I've seen before

**Comment by Tiixxel** [comment]
Yup, Clear Linux changed in many ways. I decided to give it a try and installed it on my second Desktop, but I had some issues with Steam and Flatpak because it always gave me the "failed to load steamui.so" error which is odd. Tried to fix that for hours but nothing changed. However I could install Lutris and I didn't got any errors about missing Vulkan dependencies etc. which was great.

**Comment by Tiixxel** [comment]
I reinstalled Clear Linux and Steam is now finally launching. This was weird.

**Comment by natri23** [comment]
Two notes with Clear Linux is that it doesnt have a NVIDIA's propriatery drivers installer and 2nd, you can also install dnf to get more packages.

**Comment by qiyoulu** [comment]
I recently installed Clear Linux on my old laptop and comparing to Manjaro, which I had on it before, Clear is so much faster. The new installer is very beautiful and intuitive - reminds me of the Pop OS installer. I can find everything I need in the Gnome software center (yes that thing) and installing anything is done in a blink. It's stupid fast. I haven't had any issue installing software even though they use a custom package manager (swupd) since Clear can use .rpm files.

**Comment by egee-irl** [comment]
Marking this as done ;)
