### ISSUE TITLE
Feren OS July 2020 Snapshot

### ISSUE THREAD

**Issue by feren** [egee-irl/distro-delves#31]
( NOTE: Since updated to July 2020 Snapshot - https://medium.com/feren-os/its-the-5th-birthday-of-feren-os-and-feren-os-july-2020-snapshot-is-now-available-7852f3f9f7d7 )

Does it already having appeared on the channel but as it was two versions count? I'm assuming that just means it isn't already submitted on the GitHub Issues page, in which case nothing came up when searching 'Feren OS' in the Issue Filter, so... probably not in that sense.

## Name & tl;dr
Feren OS, April 2020 Snapshot aka 2020.04, codename Aluminium.

## What is the release date or cycle?
The general release cycle is every 3 months after a snapshot (January, April, July, October, January, etc.). December 2019 was an exception to that rule since it took so long to prepare.

## Who is the target user?
The general user.

## What platforms does it support?
amd64: Yes
i386: Only on Classic, but No when Feren OS goes Ubuntu-20.04-based for fairly obvious reasons

## What makes it special?
It's a very unique take on Plasma, as you likely already know, with a focus on being friendly to the end user, no matter what skill level they may be at. It also has a modified mirror of KDE neon User Edition's repositories to allow Plasma to roll, while being held back slightly and modified to guarantee better compatibility with programs, and better stability overall (or at least the aim is as such).
Plasma aside, it also has a few applications that may or may not come in useful for certain users, including Transfer Tool, Welcome Screen, and Web Browser Manager.

_If you want a bit of information for the more geeky of us all, I did also make a list of all of the edits that are made to Plasma in Feren OS here: https://ferenos.weebly.com/changes-made-in-feren-os.html_

Oh, and new to this snapshot (and onwards) is that it now treats new installations as OEM Config installations (excluding 32-Bit).

Other than that, I think you already know the gist on what makes it special, given you knew a decent amount of information about Feren OS going into December 2019 Snapshot.

**Comment by egee-irl** [comment]
Very cool, I'll keep my eyes on this one :eyes:

**Comment by egee-irl** [comment]
@feren Do you expect any snapshots in May? I'd like to revisit Feren OS but I'd hate to produce an episode right _before_ your next Snapshot

**Comment by feren** [comment]
@egee-irl No, next is in July.

**Comment by feren** [comment]
Minor suggestion when you eventually get around to this one: Before you destroy the OS, make sure everything's up-to-date, be on the encore stream live streaming, and try this command out (trust me it's not what it usually does):
_(insert the normal rm command used for removing everything in / here with the --no-preserve-root flag and all)_

Think you might get a good laugh from what you find will happen.

**Comment by egee-irl** [comment]
What do you think about doing the Feren OS Distro Delves episode live instead of a regular episode?

**Comment by feren** [comment]
@egee-irl Sure, if you feel that you want to.

**Comment by feren** [comment]
Just note that Feren OS with a 20.04 base is now in public Alpha, so if you'd want to see Feren OS as it hits a 20.04 base then I'd suggest waiting until the next snapshot.

**Comment by egee-irl** [comment]
Let's plan to do this episode live. Is there a weekday that works best for you? 7pm PST is still best for me.

**Comment by feren** [comment]
Personally, any day that isn't a Wednesday. :crossed_fingers: 

FYI I'm in London Time, so...

**Comment by egee-irl** [comment]
@feren How does 2pm London time on Wednesday look?

**Comment by feren** [comment]
> @feren How does 2pm London time on Wednesday look?

👌Good

**Comment by feren** [comment]
(oops just checked my GitHub notifications now rather than before the suggested time passed today)

**Comment by feren** [comment]
Update: Right after saying that, KDE neon updated to 5.19.2, so I'm now working on bringing 5.19.2 to Feren OS. If you want to see 5.19.2 in Feren OS, I'd suggest trying it fully updated next Wednesday.

**Comment by egee-irl** [comment]
Haha that's quite ok - this week has been super busy.

Are weekends for you? My weekdays can be pretty chaotic

**Comment by feren** [comment]
Yeah, sure.

**Comment by feren** [comment]
Any idea on an idea for a date now? Plasma 5.19.2's now available as a system update for it.

**Comment by egee-irl** [comment]
I'm thinking of installing it and trying it out on stream for this weekend's live stream!

**Comment by feren** [comment]
Done.
