### ISSUE TITLE
Fedora Silverblue

### ISSUE THREAD

**Issue by nilsoffermann** [egee-irl/distro-delves#32]
## Name & tl;dr
Fedora Silverblue is an immutable desktop operating system aimed at replacing classical Fedora as the the preferred workstation variant
## What is the release date or cycle?
Fedora Silverblue releases alongside classical Fedora, so Silverblue 32 will be out soon
## Who is the target user?
Workstation users
## What platforms does it support?
x86_x64 and arm64
## What makes it special?
Because it's so different from package based distros and it may very well be the future of desktop/workstation Linux. Okay that may be a bit far fetched but it's a very interesting project nonetheless in my opinion. It also kinda solves the issue that we currently have to choose between up to date software and stability, because with Silverblue the system image can be rolled back and all applications are installed via Flatpak

**Comment by egee-irl** [comment]
@nilsoffermann Is it worth looking at Silverblue _instead_ of Fedora Workstation?

**Comment by nilsoffermann** [comment]
In my opinion it is worth it yeah. I think the whole concept behind Silverblue _may_ be the future of Linux on the desktop and I'd be really interested in seeing how usable it is already and how it does when you use the Distro Delves script on it. Besides that many things will be the same between the versions anyway. I don't see a reason why gaming performance should be different for example

**Comment by ishan9299** [comment]
For new users silverblue would be hell to deal with especially someone like a developer. I would recommend you to wait as a some features for silverblue are still underdevelopment. Reviewing it for distro-devels would only make an under development project seem bad.

**Comment by nilsoffermann** [comment]
You might be right about that and my point wasn't to say that "Hey this is the future we should all switch guys" but that it might be where the Linux desktop is headed in the long run and I'm interested how it already stacks up today. But having that said that you're right, it is still very much under development and a disclaimer at the beginning of the episode would be a good idea

**Comment by egee-irl** [comment]
I just wrapped up an episode on Fedora 32. How much different is Fedora Silverlight compared to episode 21?

**Comment by nilsoffermann** [comment]
I'd say the end user experience is pretty similar, because it's mostly the underlying system thta's different. But then again I haven't done any of the testing you usually do with your checklist myself, so I have no way of knowing if the perfomance in games is _actually_ the same. Besides that in Silverblue you have no more slow dnf installed and you get like 5 apps preinstalled if i remember correctly: the terminal, gnome settings, gnome software, gnome system monitor and gnome disks.

**Comment by nilsoffermann** [comment]
Oh and I just remembered, you probably won't have the weird codec issues you had in the episode with 'normal' Fedora 32 on Silverblue since every video player will be a Flatpak anyway. I mean sure, that's more a Flatpak than a Silverblue thing but in the end the experience will be different if you do the same steps
