### ISSUE TITLE
Fedora 32

### ISSUE THREAD

**Issue by koyuawsmbrtn** [egee-irl/distro-delves#34]
## Name & tl;dr

Fedora 32 Workstation (GNOME) is a RPM-based distro with good GNOME integration and a rock-solid base

## What is the release date or cycle?

Every 6 months there is a new release, the last two versions get supported, everything else dies

## Who is the target user?

Professional Linux users and everyone who wants to have a reliable system (also gamers)

## What platforms does it support?

x86_64 and aarch64

## What makes it special?

* Good GNOME integration
* [COPRs](https://copr.fedorainfracloud.org)
* [RPM Fusion](https://rpmfusion.org)
* [Easy Flatpak setup](https://flatpak.org/setup/Fedora/)
* Lutris already in the repositories (and Steam after you enabled it)
* Mesa 20 and up-to-date kernel (NVIDIA users will barely notice a difference)
* Gamemode preinstalled

## Known issues

* The first update in GNOME Software may be very slow (depending on your internet connection) and the download progress bar won't move, but every other update should go flawlessly after that. If you can't wait run `sudo dnf update` in a terminal.
* ~ABRT may spam you with crash notifications, they can be turned off in the notification settings~ [apparently fixed in Fedora 32]

**I just wanted this ticket to be open here, because I thought that letting @egee-irl know what quirks he might encounter is a good idea**

**Comment by egee-irl** [comment]
I'll take a look at this one soon ;)

**Comment by egee-irl** [comment]
Hey! We did it!
