### ISSUE TITLE
OGOS

### ISSUE THREAD

**Issue by KaiLikesLinux** [egee-irl/distro-delves#35]
## OGOS - Optimised Gaming Operating System
Version: 
![](https://i.kym-cdn.com/photos/images/facebook/001/482/738/0c3.jpg)
Github: https://github.com/debiangamer/OGOS

## What is the release date or cycle?
Rolling Release?

It was updated recently.

## Who is the target user?
Gamers

## What platforms does it support?
amd64

## What makes it special?
Weird random and unknown gaming distribution, which I think seems cool. It also has an Epic Games installer and a couple other things. "Optimized for gaming"

**Comment by egee-irl** [comment]
Oh lordy, this one might be worth looking at. Reminds me a bit of Makulu Linux

**Comment by egee-irl** [comment]
So I just tried this in a VM and on the Distro Delves PC and X appears to be broken or otherwise misconfigured out of the box, so this distro isn't going anywhere without an updated iso. Guessing the project is mostly dead at this point.
