### ISSUE TITLE
Drauger

### ISSUE THREAD

**Issue by KaiLikesLinux** [egee-irl/distro-delves#37]
## Drauger
Website: https://draugeros.org
Version: 7.4.1

## What is the release date or cycle?
Not 100% sure, seems to follow Ubuntu LTS

## Who is the target user?
Gamers

## What platforms does it support?
amd64

## What makes it special?
One of the largest gaming-focused distributions

**Comment by egee-irl** [comment]
Oh lordy

> Make Your Gaming Experience Perpetually Pleasurable

We will be looking at this distro very soon :tm:

**Comment by Batcastle** [comment]
A little more info for you, just in case it is helpful:

Press Materials
---
https://draugeros.org/go/press-materials/

Contact
---
You can contact us in any of the following ways, from fastest to slowest response times:

[Telegram Support Group](https://t.me/draugeros)
[Telegram Development Group](https://t.me/draugeros_dev)
[Discord](https://discord.gg/JW8FGrc)
[Twitter](https://twitter.com/DraugerOS)
[Email](mailto:contact@draugeros.org)

Version Change
---
On September 5th, our latest version will be version 7.5.1, and 7.4.1 will be considered End-Of-Life. You can find info about how to upgrade releases (NOT recommended) and the process of removing support for version 7.4.1 [in this blog post](https://draugeros.org/go/2020/07/24/the-7-4-1-to-7-5-1-transition/)

Thanks for considering us!

**Comment by egee-irl** [comment]
Done!
