### ISSUE TITLE
Openindiana

### ISSUE THREAD

**Issue by KaiTheCEO** [egee-irl/distro-delves#38]
## Openindiana
Version: 2020.04 
Website: https://www.openindiana.org/

## What is the release date or cycle?
Every six months, like Ubuntu. November and May are when the new versions release

## Who is the target user?
People (like me) who want a good desktop alternative to Linux

## What platforms does it support?
amd64

## What makes it special?
Based on OpenSolaris, a type of distribution you have never messed with,

**Comment by egee-irl** [comment]
Oh man this is 100% something I want to do but I'll need to spend a day or two on it to make sure I give it the review it deserves.

Do you have any ideas on which parts of the checklist will fail? Is it even worth using the standard checklist on it?

**Comment by KaiLikesLinux** [comment]
The War Thunder, Grid, and GTA5 benchmarks are the only ones I think won't work too well for benchmarking - give it a shot but make sure you disclaimer it. Also Snap, Flatpak, and AppImages seem like a bad idea (given that it is Solaris based)

Basing from the Fedora31 checklist, not much else comes to mind to remove.
