### ISSUE TITLE
BlueOS 18.04

### ISSUE THREAD

**Issue by koyuawsmbrtn** [egee-irl/distro-delves#39]
## Name & tl;dr

BlueOS 18.04, downloadable at https://blueoperatingsystem.xyz

## What is the release date or cycle?

Every new Pinguy OS release brings a new BlueOS release a few months after, this is usually when an Ubuntu LTS is proven to be stable

## Who is the target user?

People with old hardware who seek a pleasant Linux desktop experience

## What platforms does it support?

x86_64

## What makes it special?

It's my own homegrown little distro so I hope viewermade distros are also allowed?

**Comment by bubblineyuri** [comment]
I got EFI support working! :tada:

**Comment by koyuawsmbrtn** [comment]
And it fails again, nvm...also I was logged in to the wrong GitHub account, woops

**Comment by koyuawsmbrtn** [comment]
So here comes the workaround which can be found at https://blueoperatingsystem.xyz/faq.html#uefi

If you installed BlueOS over (U)EFI you have to go into your (U)EFI settings and boot the EFI file that was created. After you successfully booted up your machine open up a terminal and run the commands below to get your bootloader working.

`sudo mv /boot/efi/EFI/blueos /boot/efi/EFI/ubuntu`

**Comment by egee-irl** [comment]
Should I wait for the 20.04 update to look at this?

**Comment by koyuawsmbrtn** [comment]
No, the 18.04 release is final until I resolved some issues regarding the ISO build process for 20.04. Since this is a one-person project I may not find enough time to test things out and the 20.04 release may be released alongside Linux Mint 20 or even later. Things should work out of the box and have been patched up with PPAs until I found a good enough solution to get a 20.04 release working.

**Comment by egee-irl** [comment]
@koyuawsmbrtn What do you think of reviewing BlueOS live rather than a regular episode?

**Comment by koyuawsmbrtn** [comment]
> @koyuawsmbrtn What do you think of reviewing BlueOS live rather than a regular episode?

That would be even cooler, because I could then explain some things in the chat to you if you get some things wrong or stuff breaks that I haven't documented

**Comment by koyuawsmbrtn** [comment]
I abandoned the project, ticket closed

**Comment by egee-irl** [comment]
Let me know if you get it rolling again!

**Comment by koyuawsmbrtn** [comment]
Sure, I'm just very busy with other stuff so maintaining a distro is more work than I originally imagined.
