### ISSUE TITLE
Xubuntu 20.04

### ISSUE THREAD

**Issue by philipzae** [egee-irl/distro-delves#40]
## Xubuntu 20.04
Xubuntu is a linux distro based on Ubuntu 20.04 with Xfce desktop environment.

## What is the release date or cycle?
Xubuntu 20.04 released on 23 April 2020.

## Who is the target user?
Anyone who wants a stable, modular, and light weight desktop environments based on Ubuntu.

## What platforms does it support?
x64

## What makes it special?
An official Ubuntu flavor with one of largest communities around the Xfce desktop environment and lead by Xfce core developers.

**Comment by egee-irl** [comment]
I'd love to look at Xubuntu but people have said they want to see more non-Ubuntu distros so let's close this and open a new issue for Xubuntu 20.10
