### ISSUE TITLE
Peppermint OS 10 Respin (or if they release v11)

### ISSUE THREAD

**Issue by PadBoy** [egee-irl/distro-delves#41]
## Name & tl;dr

Peppermint OS 10 Respin

## What is the release date or cycle?

As it is based on Ubuntu 18.04 LTS, it will be "good to go" for 5 years (now 3 years). It follows its release cycle.

## Who is the target user?

Mainly it targets the beginners and low powered, old lcomputers with the combination of XFCE and LXDE desktops.

## What platforms does it support?

x86, x64

## What makes it special?

Because I think it really works for old machines. It's beginner friendly so allmost everyone  can use it for a daily basis. As ubuntu based the community support is very good.
(Also I'd like to mention about if this version (v10) is going to be the last release of this os or not? What are your thoughts about this?)

**Comment by egee-irl** [comment]
Ah yes, finally Peppermint makes an appearance!

Is it worth looking at this version when the next version is right around the corner? Should I wait or nah

**Comment by egee-irl** [comment]
@PadBoy Do you or anyone have an ETA for when version 11 will be out? People have been requesting Pep for a while and I'd love to cover it.

**Comment by PadBoy** [comment]
@egee-irl 
First, sorry for the late answer.
Unfortunately I have no idea when they will release v11. I saw a comment on YouTube that it could be the last version of this os as the lead developer is no longer with us.

**Comment by Mcpower03** [comment]
I think v11 is still on the roadmap if you wanted to wait for it, https://www.forbes.com/sites/jasonevangelho/2020/06/07/blazing-fast-and-beautiful-linux-os-peppermint-11-is-in-development/#54d1ae774f1b
