### ISSUE TITLE
Chakra Linux

### ISSUE THREAD

**Issue by Clairnet** [egee-irl/distro-delves#43]
## Name & tl;dr
Chakra Linux

## What makes it special?
Another arch based distro (i haven't tried it so thats why i have a lack of knowledge on this distro) its arch based

**Comment by egee-irl** [comment]
Oh wow, is Chakra dead? Look at the iso name - `chakra-2017.03-goedel-x86_64.iso`

I'll try it in a VM.. If it updates good, I'll see if I can run with it

**Comment by Clairnet** [comment]
> 
> 
> Oh wow, is Chakra dead? Look at the iso name - `chakra-2017.03-goedel-x86_64.iso`
> 
> I'll try it in a VM.. If it updates good, I'll see if I can run with it

possibly i've seen some recent videos about it made in 2020 but i dont know

**Comment by egee-irl** [comment]
Chakra is a bit of a mess lol. Is there anything, in particular, you'd like for me to talk about?

**Comment by Clairnet** [comment]
> 
> 
> Chakra is a bit of a mess lol. Is there anything, in particular, you'd like for me to talk about?

no its better off abandoned, my fault for not doing more research other than just looking at the distrowatch page

**Comment by egee-irl** [comment]
It's ok! I like doing reviews on abandoned or old distros. But if there's anything particular you'd like me to focus on _any_ distro, just let me know.
