### ISSUE TITLE
Manjaro 20.0 Awesome (Comunity edition)

### ISSUE THREAD

**Issue by Jitsuzai** [egee-irl/distro-delves#44]
## Name & tl;dr
Manjaro 20.0 Awesome

## Who is the target user?
Desktop users maybe power users

## What platforms does it support?
IA-32, AMD64

## What makes it special?
Distro is available on official website even when its made by comunity also the desktop enviroment is something different that most people are not familiar with

**Comment by egee-irl** [comment]
I fired it up in a VM and I don't think its a good candidate for a Distro Delves _episode_ but maybe a stand-alone Live Stream encore instead?

**Comment by Jitsuzai** [comment]
I would be fine if you would just say no, but do whatever, if you want to do a Stream I will be happy to see it.

**Comment by egee-irl** [comment]
Since I'm no good with tiling desktop environments, I think I'm going to close this one and make it a special Live episode instead, that way people can tell me how to use the damn thing :joy:
