### ISSUE TITLE
Void linux

### ISSUE THREAD

**Issue by Codythedragonrude** [egee-irl/distro-delves#46]
## Name & tl;dr

Void linux 
## What is the release date or cycle?

Rolling release
## Who is the target user?

Someone who wants to tinker with a distro outside of the typical distros as it uses runit and the live environment is barebones 
## What platforms does it support?

x86 x86_64 arm
## What makes it special?

Once you get past actually getting the distro installed and setup you will find it tends to be more stable than most rolling release distros what makes it special is just how much responsive and stable it is compared to say manjaro

**Comment by egee-irl** [comment]
Planned & on the backlog!

**Comment by egee-irl** [comment]
So according to https://alpha.de.repo.voidlinux.org/live/current/ the most recent image is from November of 2019.

Are you sure this Distro is good to look at right now or should I wait until the next release/iso drop?

**Comment by Codythedragonrude** [comment]
Yeah it's fine since all you do in the installer is install files from the iso and then when you boot into desktop as soon as you update all the packages you get the latest stuff 

if you use the xfce build you are going to get a policykit issue but you can fix that by installing elogind and then rebooting 

it's mainly because the default setup gives you a base desktop environment and then it's up to you to do everything else such as installing software and everything like that 

you don't get anything with new or old isos that makes it worth waiting for since you're most likely going to be installing software and updating stuff regardless

as i typed above it's a base desktop environment system and then you're in control of anything else you do aside from that 

it's basically the true meaning of entering the void

**Comment by egee-irl** [comment]
Ok so - Void is much like Arch in that you build it yourself. This is explicitly **not** what Distro Delves episodes are designed for because they are a huge amount of time to set up and they do not produce good footage for a _video_ because most of the configuration is done in a terminal.

Just like Arch Linux - until Void gets an _actual_ installer, we won't be seeing it on the show.
