### ISSUE TITLE
TeaLinuxOS

### ISSUE THREAD

**Issue by nakobejo** [egee-irl/distro-delves#47]
TeaLinuxOS 
## Name & tl;dr

TeaLinuxOS 11 Stevia
## What is the release date or cycle?

Fixed release maybe based on Xubuntu 18.04 lts
## Who is the target user?

Developer 
## What platforms does it support?

x64
## What makes it special?

indonesian distro, have awesome green theme

**Comment by egee-irl** [comment]
oh wow this looks awesome! Unfortunately I can't read most of the website :joy: 

Is the ISO localized?

**Comment by twilight-chan** [comment]
> oh wow this looks awesome! Unfortunately I can't read most of the website joy
> 
> Is the ISO localized?

nope the distro can be installed as english too if you wanna download just go to this url
http://pinguin.dinus.ac.id/iso/tealinuxos/TealinuxOS-11-amd64.iso

**Comment by egee-irl** [comment]
I tested it out in a VM and overall, I like what I see. I think I want to wait until the next version because there's still some rough edges here and there and I want to give the distro a fair shot on the show.

**Comment by egee-irl** [comment]
The iso Link doesn't work anymore :sob:

**Comment by nakobejo** [comment]
![gambar](https://user-images.githubusercontent.com/49896401/106341973-b2a86780-62d1-11eb-831f-8d3f6be70482.png)
maybe trying via wget?, indonesian mirror usually have some maintance

**Comment by nakobejo** [comment]
well it works again, i tried 
![gambar](https://user-images.githubusercontent.com/49896401/106359069-b58f7080-6342-11eb-959a-f551ac7126dd.png)

**Comment by dominichayesferen** [comment]
I just noticed @nakobejo has a Rikka Takanashi profile picture

You man of culture.

**Comment by nakobejo** [comment]
> I just noticed @nakobejo has a Rikka Takanashi profile picture
> 
> You man of culture.

well thats my favorite character tbh

**Comment by egee-irl** [comment]
Seems cool but the latest iso is apparently busted. maybe we can look at this later
