### ISSUE TITLE
GeckoLinux

### ISSUE THREAD

**Issue by w8487uu7848w** [egee-irl/distro-delves#48]
## Name & tl;dr

GeckoLinux

## What is the release date or cycle?

GeckoLinux is based on openSUSE. There are three editions.
- _Static_ is based on _Leap_
- _Rolling_ is based on _Tumbleweed_ 
- _Next_ is based on _Leap_, combining with additional OBS repositories

## Who is the target user?

(I think it is for) general users

## What makes it special?

openSUSE is powerful, but its OOEB is quite a mess (S2:Ep17). GeckoLinux has a focus on polish and out-of-the-box usability on the desktop. Does it live up with its goal?

**Comment by w8487uu7848w** [comment]
Since you have visited openSUSE _Tumbleweed_ with KDE, I would prefer GeckoLinux _Rolling_ with KDE being reviewed. Thanks!

**Comment by egee-irl** [comment]
The only version of Gecko that is worth looking at right now is the Tumbleweed "rolling" version. But since I already looked at Tumbleweed recently, I'm going to hold off on this for now.
