### ISSUE TITLE
CentOS

### ISSUE THREAD

**Issue by w8487uu7848w** [egee-irl/distro-delves#49]
## Name & tl;dr

CentOS 8

## What is the release date or cycle?

CentOS is a free, community-supported downstream distro of Red Hat Enterprise Linux (RHEL). There are 2 editions.
- CentOS Linux is more consistent, manageable, solid and predictable.
- CentOS Stream is a rolling-release distro, positioned as a midstream between Fedora Linux and RHEL.

## Who is the target user?

General users

## What makes it special?

Since Fedora (S2:Ep21) is the upstream distro of RHEL, aiming to be on the leading edge of free technologies, I am curious if CentOS Linux (the non-rolling-release edition) has more friendly OOEB for general users.

**Comment by egee-irl** [comment]
Of the two editions, which do you think would make the best episode?

**Comment by w8487uu7848w** [comment]
The non-rolling one. I prefer stability.
