### ISSUE TITLE
Salient OS

### ISSUE THREAD

**Issue by SkeletonsAreBad** [egee-irl/distro-delves#5]
## Name & tl;dr

Salient OS v20.02

## What is the release date or cycle?

Rolling release

## Who is the target user?

Salient is aimed at "Creative Multi-media and Gaming Enthusiasts"

## What platforms does it support?

x86_64

## What makes it special?

Salient OS wants to have the best out-of-the-box experience for users who are interesting in gaming and multi-media work. It includes software that these sorts of users might use such as OBS, Steam and Lutris and has yay for AUR support. It also claims to have it's "System Limits Optimized". (I've heard it brought up in a few different places and wanted to hear your thoughts on it)

**Comment by egee-irl** [comment]
I've been seeing this distro all over the place lately. Unless something big comes out during the production of episode 11, SalientOS will be episode 12.

**Comment by egee-irl** [comment]
I did some research on Salient OS today and I'm a little iffy about covering it on the series for two reasons - 

1) It's a vanilla Arch based distro for power users and gamers (which means it will probably "fail" most of the checklist)
2) Silent Robot is a friend in the community and I'd hate to give his distro bad publicity.

I might test it out on the Distro Delves rig some time but I'm not sure this is going to make it into season 2.

**Comment by egee-irl** [comment]
Salient OS is an episode I would want to do live _with_ Silent Robot in chat so unless he reaches out to me, I'm going to pass on this one.
