### ISSUE TITLE
Bodhi Linux

### ISSUE THREAD

**Issue by Commander-Zal** [egee-irl/distro-delves#53]
## Name & tl;dr

Bodhi Linux, version 5.1.0 

A unique Ubuntu based distro that created its own DE which manages to use less RAM than LXDE, while looking as good as KDE, and continues to offer ISOs that work with 20+ year old hardware, as well as the latest hardware on the market.

[Website Homepage](https://www.bodhilinux.com/)

## What is the release date or cycle?

The release date of 5.1.0 was March 25th, 2020, so the latest version is fairly recent. I am unsure of what their release cycle is, but as Bodhi is based on Ubuntu, I assume it's in line with the LTS version of Ubuntu.

## Who is the target user?

The target audience are users with older or resource limited hardware that don't want to sacrifice looks or usability, while retaining compatibility with Ubuntu.

## What platforms does it support?

x86 and x64.

## What makes it special?

Bodhi is rather unique for creating and using the [Moksha DE](http://www.bodhilinux.com/moksha-desktop/), which is a fork of the Enlightenment 17 DE, and is the only Distro that uses it by default. 
This makes overall resource usage _ridiculously_ low, while still offering surprisingly good looks, especially in comparison to other 'lightweight' DE's like LXQt, LXDE, or Xfce.

It also continues to offer a 32bit version (their Legacy ISO even goes so far as to disable the PAE Extension for compatibility with extremely old single core hardware, like Pentium M's), even though mainline Ubuntu, which they are based on, no longer does.

In addition, Bodhi offers an ISO specifically for newer machines (the Hwe release) , which I suspect has a more recent kernel included by default.

As its a relatively unknown distro, I suspect Delvers will be interested to see such a unique and visually appealing DE that somehow takes up less RAM than LXDE.

Overall, I'd say its one of the more interesting and unique Ubuntu based distros. :)

**Comment by egee-irl** [comment]
This looks awesome. Definitely adding it to the backlog
