### ISSUE TITLE
Add better method for calculating startup time

### ISSUE THREAD

**Issue by egee-irl** [egee-irl/distro-delves#6]
## Add, Remove, or Update?
An update

## Which Segment?
Update & Drivers

## Rationale?
The current method used, `systemd-analyze` is not always accurate. I'm not sure why, but sometimes it says a distro takes over 30 seconds to startup but the distro takes half of that.

There's probably a more robust way of calculating the startup time but I am unaware of what it is.

Please feel free to comment on this issue with ideas.

**Comment by ishan9299** [comment]
Arch wiki has good documentation regaurding analyzing the boot time using systemd-analyze with some graphs and time taken by each unit.
[boot performance](https://wiki.archlinux.org/index.php/Improving_performance/Boot_process)

**Comment by egee-irl** [comment]
Since there's not a good "standard" way of calculating this, I'm going to axe this task.
