### ISSUE TITLE
Ubuntu Lumina 20.04

### ISSUE THREAD

**Issue by KaiLikesLinux** [egee-irl/distro-delves#60]
## Ubuntu Lumina Remix
Currently, still in development but by the time, this gets seen it should be finished if not the current developer editions are relevant to what the full edition will look like and mostly has the issue of live-system for install tries to boot into Fluxbox and that should be an easy fix. Also, the Plymouth theme doesn't exist yet, but that is purely cosmetic.

## What is the release date or cycle?
Follows the Ubuntu release cycle of every April and October. 20.10 might be late, but only because of the issues behind the current release delays.

## Who is the target user?
Developers and enthusiasts. Those who want to use Ubuntu to experiment with new systems or use a lightweight Ubuntu, without the hassles of the endless settings in desktops like KDE, XFCE, and LXQt.

## What platforms does it support?
Currently AMD64 systems (64 bit AMD and Intel systems). Future editions will include RPi ARM (3/4/new 4/etc), Pine64 ARM (the main difference being some stupid bootloader issues), and editions in discussion for RISC-V and other lesser-known architectures.

## What makes it special?
It's not a remix trying to slap on a desktop environment on Ubuntu and call it a day (Like almost all the other 10 remixes and flavors), the goal is to test and innovate in different ways.

**Comment by egee-irl** [comment]
Would you rather have me wait until the final release or should I look at a beta before the official release when you think it is ready "enough"?

**Comment by KaiLikesLinux** [comment]
I am banking on the backlog of distributions to work with me here
