### ISSUE TITLE
Windowsfx

### ISSUE THREAD

**Issue by H3LLC47** [egee-irl/distro-delves#63]
Windowsfx
based on Debian/Ubuntu with heavily windows themed cinnamon desktop.

Seems like it is intended for new Linux users because of the windows 10 theme put on cinnamon

x86_64 and aarch64

https://windowsfx.org/

![2020-06-09 19_23_23-Test  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/26847529/84213766-24a01800-aa87-11ea-89d3-37f6e6a6b24d.png)

**Comment by egee-irl** [comment]
This looks really cool but it looks like Portuguese is the native (and only?) language it supports and since I don't know Portuguese, I'm unable to take a good look at this one.

**Comment by H3LLC47** [comment]
I have installed it, the website is only in Portuguese. the actual system language is English, however, I see your point.
