### ISSUE TITLE
Bunsenlabs - Helium

### ISSUE THREAD

**Issue by dapmeup** [egee-irl/distro-delves#64]
## Name & tl;dr
Bunsenlabs - Helium

## What is the release date or cycle?
I believe it follows Debian stable

## Who is the target user?
Intermediate to experienced users similar to SparkyLinux

## What platforms does it support?
i386 (i686) and amd64 (x86-64)

## What makes it special?
Extremely lightweight. Fully compatible with Debian; you can upgrade/update from one to the other.

**Comment by Mcpower03** [comment]
Is a release based on Debian 10 planned?
