### ISSUE TITLE
Linux Mint 20 "Ulyana"

### ISSUE THREAD

**Issue by shamuraix** [egee-irl/distro-delves#71]
## Name & tl;dr

Linux Mint 20 Cinnamon or Xfce
## What is the release date or cycle?

27 June 2020
## Who is the target user?

Newbies
## What platforms does it support?

x64
## What makes it special?

This release seems to be shaking things up politically, so might get a decent number of of views. Not a huge fan of Linux Mint usually to be honest though.

**Comment by shamuraix** [comment]
Just watched the episode, thanks again.

**Comment by egee-irl** [comment]
You are very welcome! I will visit the Xfce version for the next Mint release

**Comment by shamuraix** [comment]
Great news, I'm a big fan of mate but Ubuntu-Mate has been my go to for that for some time.
