### ISSUE TITLE
Artix Linux

### ISSUE THREAD

**Issue by InstantCurry** [egee-irl/distro-delves#72]
## Name and useful stuff
Artix Latest (It's rolling.) Probably an OpenRC version , since they're the most popular

## What is the release date or cycle?
Rolling. it just rolls.

## Who is the target user?
not new users. the gui installs are good, but don't have a graphical package manager out of the box.

## What platforms does it support?
x86_64. 

## What makes it special?
It's arch with a gui, and it's more stable than manjaro, because it has no custom tools.

**Comment by MrPotatoBob** [comment]
uh, what makes it special is that it does not use systemd lol

**Comment by egee-irl** [comment]
Artix doesn't have an installer does it?

**Comment by InstantCurry** [comment]
It does. Its kinda similar to manjaro in the way it deals with desktops too. The kde edition uses calimers, however you spell that

**Comment by egee-irl** [comment]
Done
