### ISSUE TITLE
BOSS Linux

### ISSUE THREAD

**Issue by sakshatshinde** [egee-irl/distro-delves#77]
## Name & tl;dr

Boss Linux  | Version : 8 (unnati)
It is a debian based distribution which targets Indian audience
[Grab it here](https://www.cdac.in/index.aspx?id=st_pr_Boss_gnu_linux)
[Website for more info - ARCHIVED](https://web.archive.org/web/20191210021356/https://www.bosslinux.in/)
## What is the release date or cycle?

Yearly 
## Who is the target user?

Government departments and General Public 
## What platforms does it support?

x86 and x64

## What makes it special?

It is specially designed for an Indian environment to offer a user friendly and secured OS with 22 official languages supported and indic keyboard layout support. 

The BOSS MOOL version aims to redesign the Linux kernel with minimal core OO components

**Comment by Beastmastah64** [comment]
if those download links are not working
try these
https://bosslinux.in/downloads - official download page
[ISO link](ftp://mirror.bosslinux.in/ISO%20Images/Desktop/unnati/boss-8.0-amd64-DVD-301019.iso)
