### ISSUE TITLE
Combine "Gaming Overview" with "Benchmarks"

### ISSUE THREAD

**Issue by egee-irl** [egee-irl/distro-delves#8]
## Add, Remove, or Update?
Remove & Update

## Which Segment?
Gaming Overview & Benchmarks

## Rationale?
Instead of showing 10 to 30 seconds of gameplay footage, I wonder if people would rather see the results of in-game benchmarks.

This is a question of anecdotes vs data.

The current Gaming Overview section is basically me saying "well, this feels like smooth fps" and I question how valuable that is.

If we used the results of benchmarks instead, I could definitively say "Distro A got better scores than Distro B".

Gaming benchmarks don't capture other issues, such as input issues or stuttering. And I don't want to do benchmarks & gameplay footage together because it would make the videos more complex and take much longer to produce.

So it's basically Gaming Benchmarks vs Gameplay Footage.

If you have any thoughts or opinions, let me know as a comment on this issue!

**Comment by Mcpower03** [comment]
I think say keep the gameplay, I would say that any big differences would show up in gameplay and smaller ones would probably be shown in benchmarks. Seeing any additional issues that happen I find more useful than tiny fps differences

**Comment by egee-irl** [comment]
I was thinking of doing gameplay of games with build-in benchmarks so I can talk about the benchmark numbers over gameplay footage. Best of both worlds?

**Comment by Mcpower03** [comment]
Numbers are great, but I feel as though things like the ps4 controller freaking out would be important things to include in the gaming section

**Comment by egee-irl** [comment]
I settled on the following resolution:

1. Merge gaming segment with benchmarking segment
2. Show gameplay footage whilst talking about the benchmark
3. Showcase a FOSS game in the outro segment

Best of both worlds!
