### ISSUE TITLE
Can you add some sort of scoring system  like how well did it complete the distro delves checklist. 

### ISSUE THREAD

**Issue by shoccho** [egee-irl/distro-delves#80]
## Add, Remove, or Update?

Add just a score like every task it completes gets the distro 1,2 points or you can add more depending on how well it performed , or you can just simple count a point if it completes.
## Which Segment?

Every ??
## Rationale?

It's quite hard to remember all the distros performance from the whole video. like someone wants to know solus and neon. If you add some sort of score like solus did 9 out 10 tasks and neon did 7 out 10 task flawlessly, then that someone can get suggestion. this example is bad because for just 2 its easy to just watch 2 videos but when you are thinking about 6-7 distro its hard to remember which distros should you consider most. (people might say  most linux distros can do what every other distro can do with a bit of tweaking but I think you always consider out of the box experience first )

**Comment by egee-irl** [comment]
I considered this early on but I decided that I didn't want Distro Delves to be about _ranking_ distros.

For example, AVGN doesn't rank video games, he just "reviews" them. That's kind of what Egee does with Distro Delves.

**Comment by shoccho** [comment]
ok understood.
