### ISSUE TITLE
The Void (Linux) distribution

### ISSUE THREAD

**Issue by argosatcore** [egee-irl/distro-delves#81]
This distro has not been requested yet.

## Name & tl;dr
 Void Linux. You can check more info at https://voidlinux.org/

## What is the release date or cycle?
 Rolling release.

## Who is the target user?
 Intermediate and advanced users.

## What platforms does it support?
 It is available for the x86, ARM and MIPS processor architectures. 

## What makes it special?
Community driven Independent distro that uses the XBPS package manager. It is Systemd free, instead, it uses Runit, which provides faster boot times. Void uses LibreSSL instead of OpenSSL, which makes it more secure by default. Unlike Arch based distros, Void focuses on stability, rather than on being bleeding-edge. Install once, update routinely and safely.

**Comment by Mcpower03** [comment]
Not to hate on void, its great and all, but someone suggested void before and egee checked it out and decided its not for the show. Just giving yoi a heads up so you know, although maybe second times the charm who knows

**Comment by egee-irl** [comment]
How would a non-installer distro work? Like, would the first 60 to 120 seconds be a terminal-based install? It just doesn't work for a Distro Delves episode.

**Comment by Waces** [comment]
It has an installer, it's a curses installer, and I think they have ISOs with desktops pre-installed. But in general it's just Arch more or less, a very minimal base with almost nothing, that the user is supposed to build on

**Comment by argosatcore** [comment]
Yes, as Waces pointed out, Void uses a ncurses installer (similar to the one used in Debian's 'advanced installation' mode), so it is between graphical and terminal based installers. Void can be installed from the base image, which will be very similar to the Arch installation process. It is also available in different 'flavors' including Cinnamon, Enlightenment, LXQT, LXDE, Matte and XFCE desktops, all of which can be booted in live mode. Another interesting fact is that Void has a very fast installation time; You literally installed the entire operating system in two minutes on a 2012 i5 machine. Here it is a picture of the installer while in live mode in the XFCE desktop.
![voidlinux_1](https://user-images.githubusercontent.com/64110504/89137330-07bb1a80-d4f5-11ea-8304-8f87bd00198b.jpg)

**Comment by egee-irl** [comment]
Oh ok, an ncurses installer could be fun.

Its the manually partitioning, running install commands, etc that don't work for episodes.

Basically, the install process has to be automated in some fashion for it to work. This ncurses thing looks cool.
