### ISSUE TITLE
deepin 20

### ISSUE THREAD

**Issue by PulkitBhardwaj1** [egee-irl/distro-delves#82]
Not covered yet.
Based on: Debian
Origin: **China**
Architecture: x86_64
Desktop: **Deepin**

You covered almost all desktop environment, so it will be new experience.
Deepin (formerly, Deepin, Linux Deepin, Hiweed GNU/Linux) is a Debian-based distribution and it has created its own desktop environment called DDE or Deepin Desktop Environment which is based on the Qt 5 toolkit. Deepin focuses much of its attention on intuitive design. Its home-grown applications, like Deepin Software Centre, DMusic and DPlayer are tailored to the average user. Being easy to install and use, deepin can be a good Windows alternative for office and home use.
_Copied from distrowatch_

**Comment by egee-irl** [comment]
Done
