### ISSUE TITLE
Haiku

### ISSUE THREAD

**Issue by Waces** [egee-irl/distro-delves#83]
## Name & tl;dr

Haiku (don't be tempted to say Haiku OS, it's just Haiku)
It's a Unix-like, building upon BeOS, to be really simple and lightweight.

Currently in Beta but there isn't a 'complete' release planned for any time soon (a year or more or so).

## What is the release date or cycle?

It's on Beta right now with not a very concrete release cycle. The newest release, Beta 2, was June of this year. Though it has nightly builds, and the main ones are getting updates often.

## Who is the target user?

General beginner to intermediate desktop users that do simple tasks, with focus on single user machines

## What platforms does it support?

x86 32 and 64 bits

## What makes it special?

It's very lightweight (a whole install being around a minute) and simple. And is inspired by BeOS (1995 - 2001), with the 32 bits build being able to run some of its programs.

**Comment by egee-irl** [comment]
Yessssss I've been wanting to look at this one for a long time.

Do you know if it will install via USB boot media? I was excited for ReactOS but unfortunately, the ReactOS bootloader doesn't work with USB devices. Hopefully its not the same with Haiku

**Comment by Waces** [comment]
It can, as shown [here](https://www.haiku-os.org/guides/installing/making_haiku_usb_stick). Though I still haven't tried myself to say how well.
