### ISSUE TITLE
(New) KDE neon on 20.04

### ISSUE THREAD

**Issue by feren** [egee-irl/distro-delves#84]
## Name & tl;dr
I think you know, already, about all of this information. Anyway, KDE neon on 20.04 appears to have been released, today!

## What is the release date or cycle?
I mean, it seems to vary with Neon when it comes to base upgrades.

## Who is the target user?
...

## What platforms does it support?
amd64, and possibly arm

## What makes it special?
Rolling KDE and Plasma

**Comment by egee-irl** [comment]
Pretty sure this won't make the cut since there are only about 10 episodes of Distro Delves left.

**Comment by egee-irl** [comment]
I've never heard of this "KDE neon" but I looked into it and it's not very interesting at all.
