### ISSUE TITLE
Zorin os 15.1 core review request

### ISSUE THREAD

**Issue by Ahmedmexx** [egee-irl/distro-delves#9]
Yes
## Name & tl;dr

Zorin os 15.1 core
## What is the release date or cycle?

Ubuntu LTS 
## Who is the target user?
new Linux users switching from Windows to linux

**Comment by egee-irl** [comment]
Did you mean Zorin 15.2? It was just released recently!

**Comment by egee-irl** [comment]
Reviewed!
