### ISSUE TITLE
mail and calender client setup, local data and cloud storage sync, cloud services accounts, RSS feeds, etc.

### ISSUE THREAD

**Issue by korbendallaskoop** [egee-irl/distro-delves#94]
This may not be distro specific as such though appropriate tools can be more or less nicely prepared by distro devs.

## Add, Remove, or Update?
Add a segment or section with PIM tools like 
mail and calender client, 
smartphone sync protocols, 
RSS feeds for news and podcasts from OPML backup, 
cloud storage sync clients and DAV folders, 
cloud service accounts for Nextcloud, Mastodon, Matrix, IRC, etc. (from Ferdi or a similar aggregator)

## Which Segment?

Either under Desktop & Drivers or as a new segment below it

## Rationale?

-to delve further into real life use cases for non-dev users. 

Was looking for something similar for LUG demo sessions. A fat, privacy cleaned, mail archive in various formats could be great to test out migration and setup. 

Fair enough if it doesn't fit your delve intentions, thanks for all your great content in any case.

**Comment by egee-irl** [comment]
These are fantastic suggestions. I will bring this issue up on the live stream this Saturday!

**Comment by korbendallaskoop** [comment]
> 
> These are fantastic suggestions. I will bring this issue up on the live stream this Saturday!

cool! I don't know which distros are making an effort setting up or forking mail clients and such, can only think of elementary, but check it out anyway, will be interesting to see what you come up with. 

Also great if it deviates away from distro check to more generic migration onboarding toolbox stuff aimed towards choosing some of the various FLOSS projects out there.

**Comment by korbendallaskoop** [comment]
a few other ideas, just to pile on while I'm at it :) :

/1
music files, when switching distro or platform, 

- how straightforward is it to edit and transfer itunes (et.al.) pls files and library
- are embedded tagging and rating formats supported 
- are string searches as deep as expected
- is the library left as is or are new and heavy db config and storage files created

/2
pst/mbox/whatever imports, 

- are folder and archive structures retained
- are mail filters and rules transferable
- are previously marked as read or deleted RSS entries (e.g. news items or podcast episodes) retained

/3
file searches, text strings against various doc formats, plus ocr of digitized (stylus) handwritten text

/4
kde connect/gsconnect phone sync of google calender, ical, webcal et.al. As above!

**Comment by egee-irl** [comment]
This is still on my radar!

**Comment by egee-irl** [comment]
I've finally added these to the checklist! Thank you so very much for these suggestions!
