### ISSUE TITLE
try `systemd-analyze critical-chain` for a top-level view of the startup sequence of services*

### ISSUE THREAD

**Issue by gregorylearns** [egee-irl/distro-delves#95]
_at least i think that what it does._

I think it's a good benchmark for how long your system boots up over time.

**Comment by natri23** [comment]
`systemd-analyze blame`

for checking startup time and services

**Comment by egee-irl** [comment]
I'll try and remember to do this for the next stream. If I forget, remind me!

**Comment by natri23** [comment]
I saw you dont know how to read systemd-analyze so here it is:

` systemd-analyze`
`Startup finished in 2.860s (firmware) + 3.034s (loader) + 978ms (kernel) + 1.712s (initrd) + 11.894s (userspace) = 20.481s
graphical.target reached after 954ms in userspace`

Basically system startup time is the total after '=' minus userspace
So in the example above, the startup time is 20.481s - 11.894s = about 9s

**Comment by egee-irl** [comment]
Finally adding this to the checklist!
