### ISSUE TITLE
Debian Testing (with more info)

### ISSUE THREAD

**Issue by Tiixxel** [egee-irl/distro-delves#96]
## Debian GNU/Linux bullseye
Debian bullseye (currently testing) is the next stable Debian release scheduled to release next Year.

## What is the release date or cycle?
It's quite difficult to explain. Technically, it's rolling release.

## Who is the target user?
Users who want to have Debian's stability and new packages.
Or they want to test out the upcoming Debian stable release.

## What platforms does it support?
It's universal

## What makes it special?
That it's basically Debian with it's stability but also with newer packages.
It also let's you choose from a huge variety of Desktop environments.

## Extra note:
_This is a duplicate of #74 ,but with more information and tips._
For simplicity, I would recommend getting the nonfree-live iso's, which can be found here: [Link](https://cdimage.debian.org/images/unofficial/non-free/images-including-firmware/weekly-live-builds/ )

**Comment by egee-irl** [comment]
All done!
